name: Auto-assign issue

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  call-workflow:
    uses: nexus-module/.github/.github/workflows/auto-assign.yml@main
    with:
      teams: devops-ia
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
